services:
  # Servicio de la aplicación NestJS
  cipil-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cipil-backend
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - MONGODB=${MONGODB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
     - ./public/uploads:/usr/src/app/public/uploads
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    networks:
      - npm
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.4'
        reservations:
          memory: 1024M
          cpus: '0.2'
networks:
  npm:
    external: true
    name: npm_network